apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    {{- include "flask-aws-monitor.labels" . | nindent 4 }}
spec:
  selector: 
    matchLabels:
      {{- include "flask-aws-monitor.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.data.replicas }}
  template:
    metadata:
      labels:
        {{- include "flask-aws-monitor.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Release.Name }}-container
        image: {{ .Values.data.image }}:{{ .Values.data.imagetag }}
        imagePullPolicy: {{ .Values.data.pullPolicy }}
        ports:
        - containerPort: {{ .Values.data.targetPort }}
        env:
        - name: AWS_ACCESS_KEY_ID
          value: "AKIAIOSFODNN7EXAMPLE"
        - name: AWS_SECRET_ACCESS_KEY
          value: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
