kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }} #from RELEASE NAME
  label: music
spec:
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.servicetype }} #from values
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
